---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
  workflow_dispatch:

jobs:
  labels:
    name: ♻️ Sync labels
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v5.0.0
        with:
          token: ${{ secrets.SYNC_LABELS_PAT }}
      - name: 🚀 Run Label Syncer
        uses: srealmoreno/label-sync-action@v2.0.0
        with:
          token: ${{ secrets.SYNC_LABELS_PAT }}
