---
name: Testing

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  jest:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24]
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v5.0.0
      - name: 🏗 Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: 🏗 Install dependencies
        run: npm ci
      - name: 🚀 Run tests
        run: npm test
